In [17]:
import pandas as pd
import requests
import os

In [18]:
global index_
index_ = [(22,'Черкаська'),(24,'Чернігівська'),(23,'Чернівецька'),(25, 'Республіка Крим'),(3, 'Дніпропетровська'),(4,'Донецька'), (8, 'Івано-Франківська'),(19, 'Харківська'),(20, 'Херсонська'),(21, 'Хмельницька'),(9,'Київська'),(26,'Київ'),(10,'Кіровоградська'),(11,'Луганська'),(12,'Львівська'),(13,'Миколаївська'),(14,'Одеська'),(15,'Полтавська'),(16,'Рівенська'),(27,'Севастополь'),(17,'Сумська'),(18,'Тернопільська'),(6,'Закарпатська'),(1,'Вінницька'),(2,'Волинська'),(7,'Запорізька'),(5,'Житомирська')]
index_ = list(enumerate(index_, start = 1))
print (index_)

[(1, (22, 'Черкаська')), (2, (24, 'Чернігівська')), (3, (23, 'Чернівецька')), (4, (25, 'Республіка Крим')), (5, (3, 'Дніпропетровська')), (6, (4, 'Донецька')), (7, (8, 'Івано-Франківська')), (8, (19, 'Харківська')), (9, (20, 'Херсонська')), (10, (21, 'Хмельницька')), (11, (9, 'Київська')), (12, (26, 'Київ')), (13, (10, 'Кіровоградська')), (14, (11, 'Луганська')), (15, (12, 'Львівська')), (16, (13, 'Миколаївська')), (17, (14, 'Одеська')), (18, (15, 'Полтавська')), (19, (16, 'Рівенська')), (20, (27, 'Севастополь')), (21, (17, 'Сумська')), (22, (18, 'Тернопільська')), (23, (6, 'Закарпатська')), (24, (1, 'Вінницька')), (25, (2, 'Волинська')), (26, (7, 'Запорізька')), (27, (5, 'Житомирська'))]

In [25]:
def download_data(index):
    url = f"https://www.star.nesdis.noaa.gov/smcd/emb/vci/VH/get_TS_admin.php?country=UKR&provinceID={index}&year1=1981&year2=2020&type=Mean"
    mas = requests.get(url)
    data = ""
    _, data = mas.text.split('<br><tt><pre>')
    data = data.replace('</pre></tt>', '')
    if int(index_[int(index)-1][1][0]) < 10:
        filename = f"0-{index_[int(index)-1][1][0]}-1981-2002.csv"
    elif (10 <= int(index_[int(index)-1][1][0])) and (int(index_[int(index)-1][1][0]) < 20):
        filename = f"1-{str(int(index_[int(index)-1][1][0])-10)}-1981-2002.csv"
    elif (20 <= int(index_[int(index)-1][1][0])):
        filename = f"2-{str(int(index_[int(index)-1][1][0])-20)}-1981-2002.csv"
    #filename = f"{index_[int(index)-1][1][0]}-1981-2002.csv"
    with open(filename, 'w') as f:
        f.write(data)

    return 0

In [26]:
def download_all_data():
    for i in range(0, 27):
        download_data(str(index_[i][0]))
        print(f"Інформація {index_[i][1][1]} завантажена")
        
download_all_data()

Інформація Черкаська завантажена
Інформація Чернігівська завантажена
Інформація Чернівецька завантажена
Інформація Республіка Крим завантажена
Інформація Дніпропетровська завантажена
Інформація Донецька завантажена
Інформація Івано-Франківська завантажена
Інформація Харківська завантажена
Інформація Херсонська завантажена
Інформація Хмельницька завантажена
Інформація Київська завантажена
Інформація Київ завантажена
Інформація Кіровоградська завантажена
Інформація Луганська завантажена
Інформація Львівська завантажена
Інформація Миколаївська завантажена
Інформація Одеська завантажена
Інформація Полтавська завантажена
Інформація Рівенська завантажена
Інформація Севастополь завантажена
Інформація Сумська завантажена
Інформація Тернопільська завантажена
Інформація Закарпатська завантажена
Інформація Вінницька завантажена
Інформація Волинська завантажена
Інформація Запорізька завантажена
Інформація Житомирська завантажена

In [28]:
def csv_directory(directory):
    df = pd.DataFrame()

    for file in os.listdir(directory):
        
        if file.endswith('.csv'):
            region1,region2, *_= file.split('-')
            dt = pd.read_csv(file, header=None)
            dt.rename(columns={0: 'рік', 1: 'тиждень', 2: 'NDVI', 3: 'BT', 4: 'VCI', 5: 'TCI', 6: 'VHI'}, inplace=True)
            for i in range(0, 27):
                if int(index_[i][1][0]) == (int(region1)*10 + int(region2)):
                   dt['область'] = index_[i][1][1] 
            dt = dt.drop(7, axis=1)
            df = df.append(dt, ignore_index=True)
    return df

df = csv_directory('.')
without_index = df[df['NDVI'] == -1].index
df = df.drop(without_index)
df = df.set_index(['область', 'рік', 'тиждень'])
df

                           NDVI      BT    VCI    TCI    VHI
область     рік  тиждень
Вінницька   1981 35       0.261  291.40   6.51  81.49  44.00
                 36       0.262  291.76  12.24  64.35  38.30
                 37       0.260  291.55  19.70  51.17  35.43
                 38       0.255  290.86  26.27  43.07  34.67
                 39       0.249  289.56  32.22  39.72  35.97
...                         ...     ...    ...    ...    ...
Севастополь 2020 34       0.382  301.26  71.47   7.74  39.61
                 35       0.375  300.70  71.15   4.64  37.90
                 36       0.367  299.74  71.30   2.73  37.02
                 37       0.361  298.66  71.86   1.59  36.72
                 38       0.352  297.57  72.20   0.72  36.46

[53487 rows x 5 columns]

In [29]:
df['VHI'].min(level=['область', 'рік'])
df

                           NDVI      BT    VCI    TCI    VHI
область     рік  тиждень
Вінницька   1981 35       0.261  291.40   6.51  81.49  44.00
                 36       0.262  291.76  12.24  64.35  38.30
                 37       0.260  291.55  19.70  51.17  35.43
                 38       0.255  290.86  26.27  43.07  34.67
                 39       0.249  289.56  32.22  39.72  35.97
...                         ...     ...    ...    ...    ...
Севастополь 2020 34       0.382  301.26  71.47   7.74  39.61
                 35       0.375  300.70  71.15   4.64  37.90
                 36       0.367  299.74  71.30   2.73  37.02
                 37       0.361  298.66  71.86   1.59  36.72
                 38       0.352  297.57  72.20   0.72  36.46

[53487 rows x 5 columns]

In [30]:
df['VHI'].max(level=['область', 'рік'])
df

                           NDVI      BT    VCI    TCI    VHI
область     рік  тиждень
Вінницька   1981 35       0.261  291.40   6.51  81.49  44.00
                 36       0.262  291.76  12.24  64.35  38.30
                 37       0.260  291.55  19.70  51.17  35.43
                 38       0.255  290.86  26.27  43.07  34.67
                 39       0.249  289.56  32.22  39.72  35.97
...                         ...     ...    ...    ...    ...
Севастополь 2020 34       0.382  301.26  71.47   7.74  39.61
                 35       0.375  300.70  71.15   4.64  37.90
                 36       0.367  299.74  71.30   2.73  37.02
                 37       0.361  298.66  71.86   1.59  36.72
                 38       0.352  297.57  72.20   0.72  36.46

[53487 rows x 5 columns]

In [87]:
df.groupby(level=['область', 'рік']).max()

                         NDVI      BT    VCI    TCI    VHI
область           рік
Івано-Франківська 1981  0.364  288.28  53.79  83.06  57.57
                  1982  0.401  293.29  50.96  78.38  53.00
                  1983  0.420  292.31  61.32  86.15  48.96
                  1984  0.439  291.90  53.03  84.08  59.05
                  1985  0.450  294.53  63.07  73.61  50.85
...                       ...     ...    ...    ...    ...
Чернігівська      2016  0.497  297.51  81.38  80.35  63.43
                  2017  0.485  296.95  79.31  73.24  65.40
                  2018  0.500  296.73  83.83  76.37  71.07
                  2019  0.487  297.66  71.47  71.76  63.12
                  2020  0.502  297.48  87.06  64.69  66.55

[1080 rows x 5 columns]

In [32]:
list(set([i[:2] for i in df[df['VHI'] < 15].index]))

[('Донецька', 1993),
 ('Луганська', 1993),
 ('Херсонська', 2003),
 ('Запорізька', 2007),
 ('Севастополь', 2000),
 ('Республіка Крим', 2012),
 ('Київ', 1999),
 ('Донецька', 1986),
 ('Луганська', 1986),
 ('Одеська', 2007),
 ('Вінницька', 2000),
 ('Сумська', 1984),
 ('Харківська', 2000),
 ('Волинська', 1994),
 ('Херсонська', 2007),
 ('Черкаська', 2000),
 ('Республіка Крим', 2007),
 ('Київська', 2000),
 ('Київ', 2000),
 ('Миколаївська', 2007)]

In [33]:
list(set([i[:2] for i in df[(df['VHI'] >= 15) & (df['VHI'] < 30)].index]))

[('Сумська', 2010),
 ('Вінницька', 1986),
 ('Одеська', 2020),
 ('Хмельницька', 1990),
 ('Вінницька', 1995),
 ('Херсонська', 2018),
 ('Рівенська', 1999),
 ('Харківська', 1986),
 ('Харківська', 1995),
 ('Севастополь', 1996),
 ('Львівська', 1989),
 ('Запорізька', 2009),
 ('Запорізька', 2018),
 ('Сумська', 1996),
 ('Дніпропетровська', 2018),
 ('Івано-Франківська', 2015),
 ('Одеська', 2015),
 ('Вінницька', 1990),
 ('Вінницька', 1999),
 ('Донецька', 2018),
 ('Рівенська', 1994),
 ('Харківська', 1990),
 ('Закарпатська', 1994),
 ('Севастополь', 1982),
 ('Львівська', 1984),
 ('Львівська', 1993),
 ('Полтавська', 2000),
 ('Сумська', 1982),
 ('Івано-Франківська', 2019),
 ('Черкаська', 1992),
 ('Одеська', 2019),
 ('Вінницька', 1994),
 ('Рівенська', 1989),
 ('Херсонська', 2017),
 ('Республіка Крим', 2002),
 ('Харківська', 1985),
 ('Республіка Крим', 2011),
 ('Республіка Крим', 2020),
 ('Закарпатська', 1989),
 ('Запорізька', 1990),
 ('Полтавська', 1986),
 ('Полтавська', 1995),
 ('Запорізька', 2017),
 ('Івано-Франківська', 1996),
 ('Дніпропетровська', 2008),
 ('Одеська', 1987),
 ('Дніпропетровська', 2017),
 ('Донецька', 1990),
 ('Черкаська', 1987),
 ('Донецька', 1999),
 ('Одеська', 2014),
 ('Херсонська', 1994),
 ('Вінницька', 1989),
 ('Херсонська', 2003),
 ('Рівенська', 1984),
 ('Донецька', 2017),
 ('Херсонська', 2012),
 ('Кіровоградська', 2014),
 ('Рівенська', 2002),
 ('Республіка Крим', 2015),
 ('Закарпатська', 1984),
 ('Закарпатська', 1993),
 ('Львівська', 1983),
 ('Полтавська', 1990),
 ('Запорізька', 2003),
 ('Полтавська', 1999),
 ('Івано-Франківська', 1982),
 ('Дніпропетровська', 1994),
 ('Запорізька', 2012),
 ('Дніпропетровська', 2003),
 ('Івано-Франківська', 2000),
 ('Одеська', 1982),
 ('Дніпропетровська', 2012),
 ('Івано-Франківська', 2009),
 ('Одеська', 1991),
 ('Донецька', 1985),
 ('Одеська', 2000),
 ('Черкаська', 1982),
 ('Донецька', 1994),
 ('Одеська', 2009),
 ('Київ', 2013),
 ('Донецька', 2003),
 ('Республіка Крим', 1983),
 ('Херсонська', 2007),
 ('Рівенська', 1988),
 ('Республіка Крим', 2001),
 ('Житомирська', 1999),
 ('Луганська', 2015),
 ('Республіка Крим', 2019),
 ('Закарпатська', 1988),
 ('Закарпатська', 1997),
 ('Чернівецька', 2009),
 ('Полтавська', 1985),
 ('Дніпропетровська', 1989),
 ('Запорізька', 2007),
 ('Івано-Франківська', 1986),
 ('Дніпропетровська', 2007),
 ('Одеська', 1986),
 ('Одеська', 1995),
 ('Донецька', 1989),
 ('Херсонська', 1984),
 ('Київ', 2008),
 ('Херсонська', 1993),
 ('Донецька', 2007),
 ('Кіровоградська', 1995),
 ('Рівенська', 1983),
 ('Херсонська', 2002),
 ('Республіка Крим', 1996),
 ('Луганська', 2010),
 ('Республіка Крим', 2005),
 ('Закарпатська', 1992),
 ('Запорізька', 1984),
 ('Миколаївська', 2020),
 ('Запорізька', 1993),
 ('Дніпропетровська', 1984),
 ('Запорізька', 2002),
 ('Тернопільська', 2015),
 ('Дніпропетровська', 1993),
 ('Дніпропетровська', 2011),
 ('Київ', 1994),
 ('Одеська', 1999),
 ('Донецька', 1993),
 ('Херсонська', 1988),
 ('Київ', 2012),
 ('Луганська', 1996),
 ('Республіка Крим', 2000),
 ('Волинська', 2002),
 ('Закарпатська', 1987),
 ('Чернівецька', 1990),
 ('Миколаївська', 2006),
 ('Миколаївська', 2015),
 ('Чернігівська', 1990),
 ('Чернігівська', 1999),
 ('Тернопільська', 2019),
 ('Чернігівська', 2008),
 ('Київ', 1989),
 ('Кіровоградська', 1985),
 ('Луганська', 1991),
 ('Республіка Крим', 1986),
 ('Луганська', 2000),
 ('Кіровоградська', 2003),
 ('Харківська', 2018),
 ('Кіровоградська', 2012),
 ('Чернівецька', 1994),
 ('Миколаївська', 2001),
 ('Миколаївська', 2019),
 ('Тернопільська', 1996),
 ('Чернігівська', 1985),
 ('Дніпропетровська', 1983),
 ('Сумська', 2019),
 ('Київ', 1984),
 ('Київ', 1993),
 ('Луганська', 1986),
 ('Кіровоградська', 1989),
 ('Луганська', 1995),
 ('Волинська', 1983),
 ('Кіровоградська', 2007),
 ('Волинська', 1992),
 ('Миколаївська', 1996),
 ('Тернопільська', 1982),
 ('Миколаївська', 2014),
 ('Тернопільська', 1991),
 ('Тернопільська', 2000),
 ('Чернігівська', 1989),
 ('Тернопільська', 2009),
 ('Київська', 1988),
 ('Київ', 1988),
 ('Хмельницька', 1994),
 ('Луганська', 1981),
 ('Харківська', 1999),
 ('Луганська', 1990),
 ('Кіровоградська', 1993),
 ('Харківська', 2008),
 ('Харківська', 2017),
 ('Волинська', 1996),
 ('Севастополь', 1991),
 ('Миколаївська', 1982),
 ('Севастополь', 2000),
 ('Миколаївська', 1991),
 ('Чернівецька', 1993),
 ('Миколаївська', 2000),
 ('Миколаївська', 2009),
 ('Тернопільська', 1986),
 ('Сумська', 2000),
 ('Чернігівська', 1984),
 ('Хмельницька', 1989),
 ('Київська', 1992),
 ('Черкаська', 2010),
 ('Київ', 1992),
 ('Черкаська', 2019),
 ('Вінницька', 2012),
 ('Хмельницька', 2016),
 ('Луганська', 1985),
 ('Луганська', 1994),
 ('Волинська', 1982),
 ('Волинська', 1991),
 ('Севастополь', 1986),
 ('Севастополь', 1995),
 ('Миколаївська', 1986),
 ('Миколаївська', 1995),
 ('Сумська', 1986),
 ('Тернопільська', 1990),
 ('Сумська', 1995),
 ('Хмельницька', 1984),
 ('Київська', 1987),
 ('Хмельницька', 1993),
 ('Вінницька', 2007),
 ('Харківська', 1989),
 ('Волинська', 1986),
 ('Севастополь', 1990),
 ('Севастополь', 1999),
 ('Сумська', 1990),
 ('Сумська', 1999),
 ('Сумська', 2008),
 ('Черкаська', 1991),
 ('Черкаська', 2000),
 ('Вінницька', 1993),
 ('Хмельницька', 1997),
 ('Харківська', 1984),
 ('Харківська', 1993),
 ('Харківська', 2011),
 ('Севастополь', 1985),
 ('Севастополь', 1994),
 ('Миколаївська', 1985),
 ('Львівська', 1996),
 ('Полтавська', 2003),
 ('Сумська', 1985),
 ('Сумська', 1994),
 ('Черкаська', 1986),
 ('Черкаська', 1995),
 ('Хмельницька', 1983),
 ('Вінницька', 1988),
 ('Вінницька', 1997),
 ('Херсонська', 2011),
 ('Рівенська', 1992),
 ('Херсонська', 2020),
 ('Вінницька', 2015),
 ('Республіка Крим', 2014),
 ('Харківська', 1997),
 ('Севастополь', 1989),
 ('Львівська', 1982),
 ('Полтавська', 1989),
 ('Львівська', 1991),
 ('Львівська', 2000),
 ('Полтавська', 2007),
 ('Запорізька', 2020),
 ('Сумська', 1989),
 ('Дніпропетровська', 2020),
 ('Донецька', 2002),
 ('Вінницька', 1992),
 ('Донецька', 2011),
 ('Рівенська', 1987),
 ('Херсонська', 2006),
 ('Черкаська', 2008),
 ('Донецька', 2020),
 ('Херсонська', 2015),
 ('Республіка Крим', 2009),
 ('Республіка Крим', 2018),
 ('Закарпатська', 1996),
 ('Полтавська', 1984),
 ('Запорізька', 1997),
 ('Львівська', 1986),
 ('Запорізька', 2006),
 ('Львівська', 1995),
 ('Івано-Франківська', 1985),
 ('Запорізька', 2015),
 ('Сумська', 1984),
 ('Івано-Франківська', 1994),
 ('Дніпропетровська', 2006),
 ('Дніпропетровська', 2015),
 ('Одеська', 1994),
 ('Одеська', 2003),
 ('Черкаська', 1985),
 ('Донецька', 1997),
 ('Одеська', 2012),
 ('Вінницька', 1987),
 ('Донецька', 2006),
 ('Рівенська', 1982),
 ('Херсонська', 2001),
 ('Вінницька', 1996),
 ('Донецька', 2015),
 ('Рівенська', 1991),
 ('Республіка Крим', 1995),
 ('Херсонська', 2019),
 ('Рівенська', 2000),
 ('Республіка Крим', 2013),
 ('Закарпатська', 1982),
 ('Закарпатська', 1991),
 ('Закарпатська', 2000),
 ('Запорізька', 1983),
 ('Запорізька', 2001),
 ('Полтавська', 1997),
 ('Запорізька', 2010),
 ('Запорізька', 2019),
 ('Одеська', 1989),
 ('Дніпропетровська', 2019),
 ('Донецька', 1983),
 ('Херсонська', 1987),
 ('Одеська', 2007),
 ('Черкаська', 1989),
 ('Вінницька', 1982),
 ('Херсонська', 1996),
 ('Вінницька', 1991),
 ('Херсонська', 2005),
 ('Рівенська', 1986),
 ('Донецька', 2019),
 ('Херсонська', 2014),
 ('Республіка Крим', 1999),
 ('Республіка Крим', 2008),
 ('Республіка Крим', 2017),
 ('Закарпатська', 1986),
 ('Запорізька', 1987),
 ('Запорізька', 1996),
 ('Львівська', 1985),
 ('Полтавська', 1992),
 ('Запорізька', 2005),
 ('Львівська', 1994),
 ('Івано-Франківська', 1984),
 ('Дніпропетровська', 1996),
 ('Запорізька', 2014),
 ('Івано-Франківська', 1993),
 ('Дніпропетровська', 2005),
 ('Дніпропетровська', 2014),
 ('Одеська', 1993),
 ('Херсонська', 1982),
 ('Київ', 2006),
 ('Донецька', 1996),
 ('Одеська', 2011),
 ('Херсонська', 2000),
 ('Херсонська', 2009),
 ('Республіка Крим', 1994),
 ('Житомирська', 1992),
 ('Луганська', 2008),
 ('Республіка Крим', 2003),
 ('Кіровоградська', 2011),
 ('Республіка Крим', 2012),
 ('Кіровоградська', 2020),
 ('Закарпатська', 1990),
 ('Запорізька', 1982),
 ('Дніпропетровська', 1982),
 ('Запорізька', 2000),
 ('Дніпропетровська', 2000),
 ('Одеська', 1988),
 ('Донецька', 1982),
 ('Київська', 2010),
 ('Херсонська', 1986),
 ('Київ', 2010),
 ('Київська', 2019),
 ('Донецька', 2000),
 ('Херсонська', 1995),
 ('Київ', 2019),
 ('Республіка Крим', 1989),
 ('Житомирська', 1987),
 ('Луганська', 2012),
 ('Республіка Крим', 2007),
 ('Кіровоградська', 2015),
 ('Волинська', 2000),
 ('Закарпатська', 1985),
 ('Чернівецька', 2015),
 ('Запорізька', 1986),
 ('Запорізька', 1995),
 ('Дніпропетровська', 1986),
 ('Дніпропетровська', 1995),
 ('Київ', 1987),
 ('Одеська', 1983),
 ('Одеська', 1992),
 ('Донецька', 1986),
 ('Донецька', 1995),
 ('Кіровоградська', 1983),
 ('Луганська', 1989),
 ('Кіровоградська', 1992),
 ('Житомирська', 1982),
 ('Республіка Крим', 1993),
 ('Житомирська', 2000),
 ('Кіровоградська', 2019),
 ('Житомирська', 2009),
 ('Чернівецька', 1983),
 ('Миколаївська', 2008),
 ('Тернопільська', 1985),
 ('Миколаївська', 2017),
 ('Тернопільська', 1994),
 ('Чернівецька', 2019),
 ('Чернігівська', 1992),
 ('Чернігівська', 2010),
 ('Київ', 1982),
 ('Чернігівська', 2019),
 ('Київська', 1991),
 ('Київська', 2000),
 ('Київ', 2000),
 ('Київська', 2009),
 ('Київ', 2009),
 ('Хмельницька', 2015),
 ('Луганська', 1984),
 ('Луганська', 1993),
 ('Республіка Крим', 1988),
 ('Кіровоградська', 1996),
 ('Житомирська', 1986),
 ('Луганська', 2011),
 ('Волинська', 1999),
 ('Луганська', 2020),
 ('Миколаївська', 1994),
 ('Миколаївська', 2003),
 ('Миколаївська', 2012),
 ('Тернопільська', 1989),
 ('Дніпропетровська', 1985),
 ('Тернопільська', 2016),
 ('Київська', 1986),
 ('Київ', 1986),
 ('Київ', 1995),
 ('Кіровоградська', 1982),
 ('Хмельницька', 2019),
 ('Луганська', 1988),
 ('Кіровоградська', 1991),
 ('Луганська', 1997),
 ('Кіровоградська', 2000),
 ('Волинська', 1985),
 ('Харківська', 2015),
 ('Волинська', 1994),
 ('Чернівецька', 1982),
 ('Миколаївська', 1989),
 ('Чернівецька', 1991),
 ('Чернівецька', 2000),
 ('Миколаївська', 2007),
 ('Чернігівська', 2000),
 ('Хмельницька', 1987),
 ('Київ', 1990),
 ('Хмельницька', 1996),
 ('Київська', 1999),
 ('Київ', 1999),
 ('Київська', 2008),
 ('Вінницька', 2019),
 ('Луганська', 1983),
 ('Кіровоградська', 1986),
 ('Харківська', 2001),
 ('Харківська', 2010),
 ('Харківська', 2019),
 ('Севастополь', 1984),
 ('Севастополь', 1993),
 ('Миколаївська', 1984),
 ('Чернівецька', 1986),
 ('Миколаївська', 1993),
 ('Миколаївська', 2011),
 ('Сумська', 1993),
 ('Сумська', 2002),
 ('Чернігівська', 1986),
 ('Хмельницька', 1982),
 ('Черкаська', 2003),
 ('Хмельницька', 1991),
 ('Хмельницька', 2000),
 ('Хмельницька', 2009),
 ('Харківська', 1996),
 ('Луганська', 1987),
 ('Волинська', 1984),
 ('Севастополь', 1988),
 ('Тернопільська', 1983),
 ('Хмельницька', 1986),
 ('Київська', 1989),
 ('Черкаська', 2007),
 ('Вінницька', 2000),
 ('Харківська', 1982),
 ('Вінницька', 2009),
 ('Луганська', 1982),
 ('Харківська', 2000),
 ('Севастополь', 1983),
 ('Миколаївська', 1983),
 ('Севастополь', 2001),
 ('Миколаївська', 1992),
 ('Сумська', 1992),
 ('Полтавська', 2019)]